// Funny name generator for auto-joining games
// Combines adjectives + nouns + optional suffixes for humorous effect

const adjectives = [
  'Sneaky', 'Fluffy', 'Grumpy', 'Sleepy', 'Bouncy', 'Wobbly', 'Sparkly',
  'Funky', 'Jazzy', 'Zesty', 'Crispy', 'Witty', 'Sassy', 'Classy',
  'Dizzy', 'Fizzy', 'Jolly', 'Merry', 'Cheeky', 'Freaky', 'Geeky',
  'Happy', 'Snappy', 'Crafty', 'Shifty', 'Swift', 'Quirky', 'Perky',
  'Gloomy', 'Dreamy', 'Creamy', 'Steam', 'Cosmic', 'Chaotic', 'Zen',
  'Turbo', 'Hyper', 'Super', 'Ultra', 'Mega', 'Nano', 'Crypto',
  'Pixel', 'Glitch', 'Retro', 'Vapor', 'Cyber', 'Neon', 'Laser',
  'Ninja', 'Pirate', 'Robot', 'Alien', 'Zombie', 'Wizard', 'Knight',
  'Lazy', 'Crazy', 'Hazy', 'Spicy', 'Icy', 'Dicey', 'Pricey',
  'Bubbly', 'Wobbly', 'Noodly', 'Googly', 'Squishy', 'Scratchy',
  'Thunder', 'Lightning', 'Stormy', 'Cloudy', 'Sunny', 'Windy',
  'Toasty', 'Roasty', 'Frosty', 'Chilly', 'Melted', 'Frozen',
  'Sizzling', 'Dazzling', 'Amazing', 'Confused', 'Amused', 'Bemused',
  'Curious', 'Furious', 'Glorious', 'Victorious', 'Mysterious',
  'Ancient', 'Modern', 'Future', 'Past', 'Lost', 'Found', 'Hidden',
  'Invisible', 'Visible', 'Obvious', 'Curious', 'Serious', 'Delirious',
]

const nouns = [
  'Panda', 'Sloth', 'Llama', 'Otter', 'Platypus', 'Narwhal', 'Axolotl',
  'Penguin', 'Moose', 'Goose', 'Mongoose', 'Walrus', 'Walnut', 'Peanut',
  'Potato', 'Tomato', 'Avocado', 'Mango', 'Taco', 'Burrito', 'Nacho',
  'Waffle', 'Pancake', 'Cupcake', 'Donut', 'Bagel', 'Pickle', 'Noodle',
  'Cookie', 'Brownie', 'Marshmallow', 'Gummybear', 'Jellybean', 'Popcorn',
  'Pumpkin', 'Squash', 'Broccoli', 'Cauliflower', 'Asparagus', 'Eggplant',
  'Unicorn', 'Dragon', 'Phoenix', 'Kraken', 'Yeti', 'Bigfoot', 'Mermaid',
  'Wizard', 'Warlock', 'Sorcerer', 'Druid', 'Ranger', 'Rogue', 'Bard',
  'Pirate', 'Captain', 'Admiral', 'General', 'Commander', 'Soldier',
  'Astronaut', 'Pilot', 'Driver', 'Rider', 'Runner', 'Jumper', 'Diver',
  'Coder', 'Hacker', 'Developer', 'Engineer', 'Architect', 'Designer',
  'Banana', 'Apple', 'Orange', 'Lemon', 'Lime', 'Cherry', 'Berry',
  'Melon', 'Coconut', 'Pineapple', 'Kiwi', 'Peach', 'Pear', 'Plum',
  'Sandwich', 'Burger', 'Pizza', 'Pasta', 'Sushi', 'Ramen', 'Curry',
  'Robot', 'Cyborg', 'Android', 'Drone', 'Bot', 'AI', 'Algorithm',
  'Ghost', 'Spirit', 'Phantom', 'Shadow', 'Specter', 'Wraith', 'Poltergeist',
  'Ninja', 'Samurai', 'Viking', 'Knight', 'Paladin', 'Monk', 'Cleric',
]

const suffixes = [
  '69', '420', '1337', '9000', 'XL', 'XXL', 'Mini', 'Max',
  'Pro', 'Plus', 'Ultra', 'Mega', 'Super', 'Hyper', 'Prime',
  'Jr', 'Sr', 'III', 'IV', 'V', 'Esquire', 'MC', 'DJ',
  'The Great', 'The Wise', 'The Brave', 'The Bold', 'The Silly',
  '2.0', 'Beta', 'Alpha', 'Omega', 'Delta', 'Sigma', 'Infinite',
  'Reloaded', 'Remastered', 'Definitive', 'Ultimate', 'Final',
  'In Space', 'On Fire', 'At Large', 'In Disguise', 'Undercover',
  'From Accounting', 'From HR', 'From IT', 'From Marketing',
  'Of Doom', 'Of Destiny', 'Of Glory', 'Of Chaos', 'Of Wonder',
]

// Generate a deterministic but seemingly random name based on a seed
function seededRandom(seed: number): number {
  const x = Math.sin(seed) * 10000
  return x - Math.floor(x)
}

// Generate a funny name with optional seed for determinism
export function generateFunnyName(seed?: number): string {
  const useSeed = seed ?? Date.now() + Math.random() * 10000

  const adjIndex = Math.floor(seededRandom(useSeed) * adjectives.length)
  const nounIndex = Math.floor(seededRandom(useSeed + 1) * nouns.length)
  const hasSuffix = seededRandom(useSeed + 2) > 0.6 // 40% chance of suffix

  let name = `${adjectives[adjIndex]}${nouns[nounIndex]}`

  if (hasSuffix) {
    const suffixIndex = Math.floor(seededRandom(useSeed + 3) * suffixes.length)
    const suffix = suffixes[suffixIndex]
    // Some suffixes need space, others don't
    if (suffix.startsWith('The') || suffix.startsWith('From') || suffix.startsWith('Of')) {
      name += ` ${suffix}`
    } else if (/^\d/.test(suffix)) {
      name += suffix
    } else {
      name += suffix
    }
  }

  return name
}

// Generate multiple unique funny names
export function generateUniqueFunnyNames(count: number): string[] {
  const names = new Set<string>()
  let attempts = 0
  const maxAttempts = count * 10

  while (names.size < count && attempts < maxAttempts) {
    names.add(generateFunnyName(Date.now() + attempts))
    attempts++
  }

  return Array.from(names)
}

// Check if a name looks auto-generated (for UI hints)
export function isAutoGeneratedName(name: string): boolean {
  // Check if it matches our pattern: AdjectiveNoun or AdjectiveNounSuffix
  const pattern = /^[A-Z][a-z]+[A-Z][a-z]+(\s.+|\d+|\w+)?$/
  return pattern.test(name)
}
