'use client'

import { useState, useEffect, useCallback } from 'react'
import { generateFunnyName } from '@/lib/funnyNames'

// Only the player's name is persisted — no UUID in localStorage.
// The server resolves the DB UUID from (gameId, playerName) on every operation,
// eliminating stale-UUID bugs caused by cross-game localStorage pollution.
const PLAYER_NAME_KEY = 'planning_poker_player_name'
const AUTO_GENERATED_KEY = 'planning_poker_auto_generated_name'

export function usePlayer() {
  const [playerName, setPlayerName] = useState<string>('')
  const [isAutoGenerated, setIsAutoGenerated] = useState<boolean>(false)
  const [isInitialized, setIsInitialized] = useState<boolean>(false)

  useEffect(() => {
    const storedName = localStorage.getItem(PLAYER_NAME_KEY)
    const wasAutoGenerated = localStorage.getItem(AUTO_GENERATED_KEY) === 'true'

    if (storedName) setPlayerName(storedName)
    setIsAutoGenerated(wasAutoGenerated)
    setIsInitialized(true)
  }, [])

  /** Store a chosen name (manual join). */
  const updateName = useCallback((name: string) => {
    setPlayerName(name)
    setIsAutoGenerated(false)
    localStorage.setItem(PLAYER_NAME_KEY, name)
    localStorage.setItem(AUTO_GENERATED_KEY, 'false')
  }, [])

  /** Auto-create a player with a funny random name. */
  const autoCreatePlayer = useCallback(() => {
    const funnyName = generateFunnyName()
    setPlayerName(funnyName)
    setIsAutoGenerated(true)
    localStorage.setItem(PLAYER_NAME_KEY, funnyName)
    localStorage.setItem(AUTO_GENERATED_KEY, 'true')
    return { name: funnyName }
  }, [])

  /** Clear all local player state (e.g., on leave). */
  const clearPlayer = useCallback(() => {
    setPlayerName('')
    setIsAutoGenerated(false)
    localStorage.removeItem(PLAYER_NAME_KEY)
    localStorage.removeItem(AUTO_GENERATED_KEY)
  }, [])

  return {
    playerName,
    isAutoGenerated,
    isInitialized,
    updateName,
    autoCreatePlayer,
    clearPlayer,
  }
}
