'use client'

import { useState, useEffect, useCallback } from 'react'
import { v4 as uuidv4 } from 'uuid'
import { generateFunnyName } from '@/lib/funnyNames'

const PLAYER_STORAGE_KEY = 'planning_poker_player_id'
const PLAYER_NAME_KEY = 'planning_poker_player_name'
const AUTO_GENERATED_KEY = 'planning_poker_auto_generated_name'

export function usePlayer() {
  const [playerId, setPlayerId] = useState<string | null>(null)
  const [playerName, setPlayerName] = useState<string>('')
  const [isAutoGenerated, setIsAutoGenerated] = useState<boolean>(false)
  const [isInitialized, setIsInitialized] = useState<boolean>(false)

  useEffect(() => {
    // Load existing player ID from localStorage
    const storedId = localStorage.getItem(PLAYER_STORAGE_KEY)
    const storedName = localStorage.getItem(PLAYER_NAME_KEY)
    const wasAutoGenerated = localStorage.getItem(AUTO_GENERATED_KEY) === 'true'

    if (storedId) {
      setPlayerId(storedId)
    }
    if (storedName) {
      setPlayerName(storedName)
    }
    setIsAutoGenerated(wasAutoGenerated)
    setIsInitialized(true)
  }, [])

  const createPlayer = useCallback((name: string) => {
    const id = uuidv4()
    setPlayerId(id)
    setPlayerName(name)
    setIsAutoGenerated(false)
    localStorage.setItem(PLAYER_STORAGE_KEY, id)
    localStorage.setItem(PLAYER_NAME_KEY, name)
    localStorage.setItem(AUTO_GENERATED_KEY, 'false')
    return { id, name }
  }, [])

  // Auto-create a player with a funny random name
  const autoCreatePlayer = useCallback(() => {
    const funnyName = generateFunnyName()
    const id = uuidv4()
    setPlayerId(id)
    setPlayerName(funnyName)
    setIsAutoGenerated(true)
    localStorage.setItem(PLAYER_STORAGE_KEY, id)
    localStorage.setItem(PLAYER_NAME_KEY, funnyName)
    localStorage.setItem(AUTO_GENERATED_KEY, 'true')
    return { id, name: funnyName }
  }, [])

  const updateName = useCallback((name: string) => {
    setPlayerName(name)
    setIsAutoGenerated(false)
    localStorage.setItem(PLAYER_NAME_KEY, name)
    localStorage.setItem(AUTO_GENERATED_KEY, 'false')
  }, [])

  const syncPlayerId = useCallback((id: string) => {
    setPlayerId(id)
    localStorage.setItem(PLAYER_STORAGE_KEY, id)
  }, [])

  const clearPlayer = useCallback(() => {
    setPlayerId(null)
    setPlayerName('')
    setIsAutoGenerated(false)
    localStorage.removeItem(PLAYER_STORAGE_KEY)
    localStorage.removeItem(PLAYER_NAME_KEY)
    localStorage.removeItem(AUTO_GENERATED_KEY)
  }, [])

  return {
    playerId,
    playerName,
    isAutoGenerated,
    isInitialized,
    createPlayer,
    autoCreatePlayer,
    updateName,
    syncPlayerId,
    clearPlayer,
  }
}
