'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { PokerCardDeck, FlyingCard } from './PokerCard'
import { PokerTable } from './PokerTable'
import { useGame } from '@/hooks/useGame'
import { usePlayer } from '@/hooks/usePlayer'
import { useWebSocketPresence } from '@/hooks/useWebSocketPresence'
import { useState, useEffect, useMemo, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { supabase, submitVote, resetVotes, updateGameStatus } from '@/lib/supabase'
import { COFFEE_CARD, type Vote } from '@/types'

const LAST_GAME_ID_KEY = 'planning_poker_last_game_id'

interface GameRoomProps {
  gameId: string
}

export function GameRoom({ gameId }: GameRoomProps) {
  const router = useRouter()
  const { game, players, issues, votes, isLoading, error, refreshGame, updateGameStatus: setStatus, setVotes } = useGame(gameId)
  const { playerId, playerName, isAutoGenerated, isInitialized, autoCreatePlayer, updateName, syncPlayerId } = usePlayer()
  const { socket, isConnected, isPlayerActive, presence } = useWebSocketPresence(gameId, playerId, playerName || '')

  // Find current player from players list — match by ID first, fall back to name
  const currentPlayer = useMemo(() => {
    return players.find(p => p.id === playerId) || players.find(p => p.name === playerName) || null
  }, [players, playerId, playerName])

  // Debug presence
  useEffect(() => {
    console.log('Presence map:', Array.from(presence.entries()))
  }, [presence])
  const [selectedCard, setSelectedCard] = useState<number | typeof COFFEE_CARD | null>(null)
  const [hasVoted, setHasVoted] = useState(false)
  const [newIssueTitle, setNewIssueTitle] = useState('')
  const [showIssueInput, setShowIssueInput] = useState(false)
  const [showNameEditor, setShowNameEditor] = useState(false)
  const [nameEditInput, setNameEditInput] = useState('')
  
  // Flying card animation state
  const [flyingCard, setFlyingCard] = useState<{
    value: number | typeof COFFEE_CARD
    startX: number
    startY: number
    endX: number
    endY: number
  } | null>(null)
  const [pendingVote, setPendingVote] = useState<{
    value: number | typeof COFFEE_CARD
    playerId: string
    issueId: string
    timestamp: number
  } | null>(null)
  const [wasRemoved, setWasRemoved] = useState(false)

  const currentIssue = issues.find(i => i.status === 'voting') || issues[0]
  const currentVotes = useMemo(() => {
    return currentIssue ? (votes[currentIssue.id] || []) : []
  }, [currentIssue, votes])

  // Check if current player has voted and detect if removed by someone else
  useEffect(() => {
    const existingPlayer = players.find(p => p.name === playerName)
    if (existingPlayer) {
      const playerHasVoted = !!currentVotes.some(v => v.player_id === existingPlayer.id)
      setHasVoted(playerHasVoted)
      
      // Clear pending vote once DB confirms the vote
      if (playerHasVoted && pendingVote && pendingVote.playerId === existingPlayer.id) {
        setPendingVote(null)
      }
    } else if (playerName && !wasRemoved) {
      // Player name exists but player not in list - they were removed by someone else
      console.log('Detected player removal by facilitator')
      setWasRemoved(true)
    }
  }, [currentVotes, players, playerName, pendingVote, wasRemoved])

  // Reset voting state when issue changes
  useEffect(() => {
    setSelectedCard(null)
    setHasVoted(false)
  }, [currentIssue?.id])

  // Auto-join game if player ID exists (but not if they were just removed)
  useEffect(() => {
    if (wasRemoved) return // Don't rejoin if player was removed
    
    if (playerId && gameId && !players.find(p => p.id === playerId)) {
      // Check if we already have a player in this game with our name
      const existingPlayer = players.find(p => p.name === playerName)
      if (existingPlayer) {
        // We already have a player in this game, sync localStorage to use it
        console.log('Found existing player in game, syncing ID:', existingPlayer)
        syncPlayerId(existingPlayer.id)
        return // Don't create a new player
      }

      // Player not in game yet, add them
      supabase
        .from('players')
        .insert({
          game_id: gameId,
          name: playerName || 'Anonymous',
          is_facilitator: players.length === 0, // First player is facilitator
        })
        .select()
        .single()
        .then(({ data, error }) => {
          if (data) {
            console.log('Joined game:', data)
          }
          if (error) {
            console.error('Failed to join game:', error)
          }
        })
    }
  }, [playerId, playerName, gameId, players, syncPlayerId, wasRemoved])
  
  // Reset wasRemoved when game changes
  useEffect(() => {
    setWasRemoved(false)
  }, [gameId])

  const handleUpdateName = async () => {
    const newName = nameEditInput.trim()
    if (!newName) return

    const targetId = currentPlayer?.id || playerId
    if (!targetId) return

    console.log('Attempting to rename:', { targetId, newName, gameId, currentPlayer, playerId })

    // Get all players in this game to check for duplicates
    const { data: allPlayers, error: fetchError } = await supabase
      .from('players')
      .select('id, name')
      .eq('game_id', gameId)

    if (fetchError) {
      console.error('Failed to fetch players:', fetchError)
    }

    console.log('All players in game:', allPlayers)

    // Check for duplicate (exact case-sensitive match like the DB constraint)
    const duplicate = allPlayers?.find(p => p.name === newName && p.id !== targetId)
    
    if (duplicate) {
      console.log('Duplicate found:', duplicate)
      alert(`The name "${newName}" is already taken by player ID: ${duplicate.id}`)
      return
    }

    const oldName = playerName

    // Update in database FIRST (before updating local state to avoid race conditions)
    const { data, error } = await supabase
      .from('players')
      .update({ name: newName })
      .eq('id', targetId)
      .select()
      .single()

    if (error) {
      console.error('Failed to update name:', error)
      console.error('Error details:', JSON.stringify(error, null, 2))
      console.log('All players after failed update:', allPlayers)
      alert(`Failed to update name: ${error.message}`)
    } else {
      console.log('Name updated successfully:', data)
      // Update local state AFTER successful database update
      updateName(newName)
      setShowNameEditor(false)
    }
  }

  const openNameEditor = () => {
    setNameEditInput(playerName)
    setShowNameEditor(true)
  }

  const handleRemovePlayer = async (playerIdToRemove: string) => {
    const currentPlayerData = players.find(p => p.name === playerName)
    const isFacilitator = currentPlayerData?.is_facilitator || false
    const isSelf = players.find(p => p.id === playerIdToRemove)?.name === playerName

    if (!isFacilitator && !isSelf) {
      alert('Only facilitators can remove other players')
      return
    }

    if (confirm('Are you sure you want to remove this player?')) {
      // Mark as removed if removing self to prevent auto-rejoin
      if (isSelf) {
        setWasRemoved(true)
      }
      
      const { error } = await supabase
        .from('players')
        .delete()
        .eq('id', playerIdToRemove)

      if (error) {
        console.error('Failed to remove player:', error)
        alert('Failed to remove player')
        // Reset wasRemoved on error so they can rejoin if needed
        if (isSelf) {
          setWasRemoved(false)
        }
      }
    }
  }

  const handleCardClick = async (value: number | typeof COFFEE_CARD, cardRect: DOMRect) => {
    if (!playerId) {
      alert('You need to join the game first.')
      return
    }
    // Allow changing card even if already voted (before reveal)
    if (game?.status === 'revealed') {
      alert('Voting has ended. Cannot change your vote.')
      return
    }

    // Check if player exists in this game
    const existingPlayer = players.find(p => p.name === playerName)
    if (!existingPlayer) {
      alert('You need to join the game first. Please refresh the page.')
      return
    }

    // Get card position (start of animation)
    const startPosition = {
      x: cardRect.left + cardRect.width / 2 - 28, // Center the 56px card (w-14 = 56px)
      y: cardRect.top + cardRect.height / 2 - 40, // Center the 80px card (h-20 = 80px)
    }

    // Find player's card slot on the table (end of animation)
    const playerCardEl = document.querySelector(`[data-player-card="${existingPlayer.id}"]`)
    let endPosition = { x: window.innerWidth / 2, y: window.innerHeight / 2 }
    
    if (playerCardEl) {
      const slotRect = playerCardEl.getBoundingClientRect()
      endPosition = {
        x: slotRect.left + slotRect.width / 2 - 28,
        y: slotRect.top + slotRect.height / 2 - 40,
      }
    }

    // Start flying card animation
    setFlyingCard({
      value,
      startX: cardRect.left + cardRect.width / 2 - 28,
      startY: cardRect.top + cardRect.height / 2 - 40,
      endX: endPosition.x,
      endY: endPosition.y,
    })
    setSelectedCard(value)

    // Wait for animation to complete before showing face-down card and submitting vote
    // The pending vote and submission happens in handleFlyingCardComplete
  }

  const handleFlyingCardComplete = async () => {
    if (!flyingCard) return

    const existingPlayer = players.find(p => p.name === playerName)
    if (!existingPlayer) return

    // Show face-down card immediately when animation completes (before DB submission)
    if (currentIssue) {
      setPendingVote({
        value: flyingCard.value,
        playerId: existingPlayer.id,
        issueId: currentIssue.id,
        timestamp: Date.now(),
      })
    }

    // Auto-create a default issue if none exists
    let issueId = currentIssue?.id
    if (!issueId) {
      const { data: newIssue, error: issueError } = await supabase
        .from('issues')
        .insert({
          game_id: gameId,
          title: 'Current Task',
          status: 'voting',
          order: issues.length,
        })
        .select()
        .single()

      if (issueError) {
        console.error('Failed to create issue:', issueError)
        alert('Failed to create voting session')
        setSelectedCard(null)
        setFlyingCard(null)
        return
      }
      issueId = newIssue.id
      // Update game status to voting
      await setStatus('voting')
    }

    try {
      console.log('Submitting vote:', { gameId, issueId, playerId: existingPlayer.id, value: flyingCard.value })
      await submitVote(gameId, issueId, existingPlayer.id, typeof flyingCard.value === 'number' ? flyingCard.value : -1)
      setHasVoted(true)
      
      // Broadcast card placement animation to other players via WebSocket
      if (socket) {
        socket.emit('card-placed', {
          gameId,
          playerId: existingPlayer.id,
          playerName,
          cardValue: flyingCard.value,
        })
      }
    } catch (error) {
      console.error('Failed to submit vote:', error)
      console.error('Error details:', JSON.stringify(error, null, 2))
      const errorMessage = error instanceof Error ? error.message : String(error)
      alert(`Failed to submit vote: ${errorMessage}`)
      // Reset on error
      setSelectedCard(null)
    } finally {
      // Clear flying card after submission
      // Note: pendingVote is NOT cleared here - it stays until DB confirms
      // to prevent the flicker from face-down -> empty -> face-down
      setFlyingCard(null)
    }
  }

  const handleReveal = async () => {
    if (!game) return
    await setStatus('revealed')
  }

  const handleResetVotes = async () => {
    if (!currentIssue) return
    await resetVotes(gameId, currentIssue.id)
    await setStatus('voting') // Change status back to voting
    // Clear local votes immediately to update UI
    setVotes(prev => ({ ...prev, [currentIssue.id]: [] }))
    setSelectedCard(null)
    setHasVoted(false)
  }

  const handleNextIssue = async () => {
    if (!currentIssue) return

    // Mark current issue as completed
    await supabase
      .from('issues')
      .update({ status: 'completed' })
      .eq('id', currentIssue.id)

    // Find next pending issue
    const nextIssue = issues.find(i => i.status === 'pending' && i.id !== currentIssue.id)

    if (nextIssue) {
      await supabase
        .from('issues')
        .update({ status: 'voting' })
        .eq('id', nextIssue.id)
      await setStatus('voting')
    } else {
      await setStatus('lobby')
    }

    setSelectedCard(null)
    setHasVoted(false)
  }

  const handleAddIssue = async () => {
    if (!newIssueTitle.trim()) return

    const isFirstIssue = issues.length === 0
    
    const { error } = await supabase
      .from('issues')
      .insert({
        game_id: gameId,
        title: newIssueTitle.trim(),
        status: isFirstIssue ? 'voting' : 'pending',
        order: issues.length,
      })

    if (!error) {
      setNewIssueTitle('')
      setShowIssueInput(false)
      // Set game status to voting when first issue is added
      if (isFirstIssue) {
        await setStatus('voting')
        refreshGame()
      }
    }
  }

  const calculateConsensus = () => {
    if (currentVotes.length === 0) return null

    const numericVotes = currentVotes
      .map(v => v.points)
      .filter(p => p >= 0) // Filter out coffee cards

    if (numericVotes.length === 0) return null

    const avg = numericVotes.reduce((a, b) => a + b, 0) / numericVotes.length
    const uniqueVotes = new Set(numericVotes)

    return {
      average: avg.toFixed(1),
      consensus: uniqueVotes.size === 1,
      votes: numericVotes,
      coffeeBreaks: currentVotes.filter(v => v.points < 0).length,
    }
  }

  const consensus = calculateConsensus()

  // Auto-create player on first visit - no join screen needed
  // MUST be before any early returns to follow React hooks rules
  useEffect(() => {
    if (isInitialized && !playerId && !isLoading) {
      autoCreatePlayer()
    }
  }, [isInitialized, playerId, isLoading, autoCreatePlayer])

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-secondary text-lg">Loading game...</div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-error text-lg">{error}</div>
      </div>
    )
  }

  if (!playerId || !isInitialized) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-surface rounded-lg border border-border elevation-medium p-8 max-w-md w-full text-center"
        >
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
            className="w-12 h-12 border-4 border-neutral-light border-t-primary rounded-full mx-auto mb-4"
          />
          <h2 className="text-xl font-semibold text-secondary mb-2">Joining game...</h2>
          <p className="text-neutral">Generating your nickname!</p>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="bg-surface border-b border-border elevation-low sticky top-0 z-50">
        <div className="px-4 py-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div>
                <h1 className="text-lg font-semibold text-secondary">{game?.name}</h1>
                <p className="text-xs text-neutral">Game ID: {gameId}</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              {/* Player avatars */}
              <div className="flex -space-x-2">
                {players.map((player) => {
                  const isActive = isPlayerActive(player.id)
                  const isCurrentPlayer = player.name === playerName

                  return (
                    <div key={player.id} className="relative group">
                      <div
                        className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold border-2 border-surface elevation-low ${
                          isActive ? 'bg-primary' : 'bg-neutral'
                        }`}
                        title={`${player.name} ${isActive ? '(online)' : '(offline)'}`}
                      >
                        {player.name.charAt(0).toUpperCase()}
                      </div>

                      {isActive && (
                        <div className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-success rounded-full border-2 border-surface" />
                      )}

                      {!isActive && (isCurrentPlayer || players.find(p => p.name === playerName)?.is_facilitator) && (
                        <button
                          onClick={() => handleRemovePlayer(player.id)}
                          className="absolute -top-2 -right-2 w-5 h-5 bg-error hover:bg-red-600 rounded-full flex items-center justify-center text-white text-xs opacity-0 group-hover:opacity-100 transition-opacity border-2 border-surface z-10"
                          title="Remove player"
                        >
                          ×
                        </button>
                      )}
                    </div>
                  )
                })}
              </div>

              {/* Player count badge */}
              <div className="px-2 py-1 bg-neutral-light rounded text-xs font-medium text-secondary">
                {players.length} {players.length === 1 ? 'player' : 'players'}
              </div>

              {/* Current player name with edit button */}
              <button
                onClick={openNameEditor}
                className="flex items-center gap-2 px-3 py-1.5 bg-neutral-light hover:bg-neutral-200 rounded transition-colors group"
                title="Click to edit your name"
              >
                <span className="text-neutral text-xs">Playing as:</span>
                <span className="text-secondary font-medium text-sm">{playerName}</span>
                <svg
                  className="w-3.5 h-3.5 text-neutral group-hover:text-secondary transition-colors"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                </svg>
              </button>

              {/* Leave Game button */}
              <button
                onClick={() => {
                  if (confirm('Leave this game? You can always rejoin later.')) {
                    localStorage.removeItem('planning_poker_last_game_id')
                    window.location.href = '/'
                  }
                }}
                className="px-3 py-1.5 bg-neutral-light hover:bg-red-50 text-neutral hover:text-error rounded transition-colors text-sm font-medium"
                title="Leave game"
              >
                Leave
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Name Editor Modal */}
      <AnimatePresence>
        {showNameEditor && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-neutral-dark/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setShowNameEditor(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-surface rounded-lg border border-border elevation-high p-6 max-w-md w-full"
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className="text-xl font-semibold text-secondary mb-2">Edit Your Name</h3>
              <p className="text-neutral text-sm mb-4">
                You were automatically assigned a fun name! Change it if you like.
              </p>
              <div className="space-y-4">
                <input
                  type="text"
                  value={nameEditInput}
                  onChange={(e) => setNameEditInput(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleUpdateName()}
                  className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                  autoFocus
                  maxLength={30}
                />
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowNameEditor(false)}
                    className="flex-1 py-2 bg-neutral-light hover:bg-neutral-200 rounded text-secondary font-medium transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleUpdateName}
                    disabled={!nameEditInput.trim() || nameEditInput.trim() === playerName}
                    className="flex-1 py-2 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-medium transition-colors"
                  >
                    Save
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="px-4 py-6">
        <div className="grid lg:grid-cols-4 gap-6 max-w-7xl mx-auto">
          {/* Main Game Area */}
          <div className="lg:col-span-3 space-y-6">
            {/* Current Issue */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-surface rounded-lg border border-border elevation-medium p-6"
            >
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h2 className="text-lg font-semibold text-secondary">
                    {currentIssue ? currentIssue.title : 'No Issue Selected'}
                  </h2>
                  <div className="flex items-center gap-2 mt-1 h-6">
                    {currentIssue ? (
                      <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
                        currentIssue.status === 'voting'
                          ? 'bg-blue-light text-primary'
                          : currentIssue.status === 'completed'
                          ? 'bg-green-light text-success'
                          : 'bg-neutral-light text-neutral'
                      }`}>
                        {currentIssue.status}
                      </span>
                    ) : (
                      <span className="opacity-0 inline-flex items-center px-2 py-0.5 rounded text-xs font-medium">
                        placeholder
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {currentIssue?.description && (
                <p className="text-neutral mb-6">{currentIssue.description}</p>
              )}

              {/* Poker Table with Players */}
              <div className="mb-8">
                <PokerTable
                  players={players}
                  currentPlayerName={playerName || ''}
                  currentPlayerId={currentPlayer?.id || null}
                  votes={votes}
                  currentIssueId={currentIssue?.id || null}
                  isRevealed={game?.status === 'revealed'}
                  isPlayerActive={isPlayerActive}
                  gameId={gameId}
                  pendingVote={pendingVote}
                />
              </div>

              {/* Voting Cards */}
              {(game?.status === 'voting' || game?.status === 'lobby') && (
                <div className="text-center border-t border-border pt-6">
                  <p className="text-neutral mb-4 h-6 flex items-center justify-center">
                    {hasVoted ? (
                      <span className="inline-flex items-center gap-1 animate-fade-in">
                        <svg className="w-4 h-4 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        Vote submitted! Change your vote anytime below
                      </span>
                    ) : (
                      <span className="opacity-0">Vote submitted! Change your vote anytime below</span>
                    )}
                  </p>
                  <PokerCardDeck
                    selectedValue={selectedCard}
                    onCardClick={handleCardClick}
                    disabled={flyingCard !== null}
                    animatingCard={flyingCard?.value ?? null}
                  />
                </div>
              )}

              {/* Flying Card Animation */}
              <AnimatePresence>
                {flyingCard && (
                  <FlyingCard
                    value={flyingCard.value}
                    startRect={{
                      left: flyingCard.startX,
                      top: flyingCard.startY,
                      width: 56,
                      height: 80,
                    }}
                    endRect={{
                      left: flyingCard.endX,
                      top: flyingCard.endY,
                      width: 56,
                      height: 80,
                    }}
                    onComplete={handleFlyingCardComplete}
                  />
                )}
              </AnimatePresence>

              {/* Reveal Phase Results */}
              {game?.status === 'revealed' && currentVotes.length > 0 && (
                <div className="space-y-6 border-t border-border pt-6">
                  {/* Consensus Results */}
                  {consensus && (
                    <motion.div
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      className={`rounded-lg p-4 text-center border-2 ${
                        consensus.consensus
                          ? 'bg-green-light border-success/30'
                          : 'bg-yellow-light border-warning/30'
                      }`}
                    >
                      <h4 className="text-lg font-semibold text-secondary mb-2">
                        {consensus.consensus ? '🎉 Consensus Reached!' : '🤔 Different Estimates'}
                      </h4>
                      <p className="text-neutral mb-1">
                        Average: <span className="font-bold text-primary">{consensus.average}</span> points
                      </p>
                      {consensus.coffeeBreaks > 0 && (
                        <p className="text-neutral text-sm">
                          ☕ {consensus.coffeeBreaks} player(s) took a coffee break
                        </p>
                      )}
                    </motion.div>
                  )}

                  {/* Action Buttons */}
                  <div className="flex justify-center gap-3">
                    <button
                      onClick={handleResetVotes}
                      className="px-5 py-2 bg-neutral-light hover:bg-neutral-200 rounded text-secondary font-medium transition-colors"
                    >
                      Revote
                    </button>
                    <button
                      onClick={handleNextIssue}
                      className="px-5 py-2 bg-primary hover:bg-blue-600 rounded text-white font-medium transition-colors"
                    >
                      Next Issue
                    </button>
                  </div>
                </div>
              )}

              {/* Reveal Button */}
              {(game?.status === 'voting' || game?.status === 'lobby') && currentVotes.length > 0 && (
                <div className="text-center mt-6 pt-6 border-t border-border">
                  <button
                    onClick={handleReveal}
                    disabled={currentVotes.length < players.length}
                    className="px-6 py-2.5 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-medium transition-colors"
                  >
                    Reveal Votes ({currentVotes.length}/{players.length})
                  </button>
                </div>
              )}
            </motion.div>
          </div>

          {/* Sidebar - Issues List */}
          <div className="lg:col-span-1">
            <div className="bg-surface rounded-lg border border-border elevation-medium p-4 sticky top-20">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-base font-semibold text-secondary">Issues</h3>
                <button
                  onClick={() => setShowIssueInput(!showIssueInput)}
                  className="px-2.5 py-1.5 bg-primary hover:bg-blue-600 rounded text-white text-sm font-medium transition-colors inline-flex items-center gap-1"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                  Add
                </button>
              </div>

              {/* Add Issue Input */}
              {showIssueInput && (
                <div className="mb-3 space-y-2">
                  <input
                    type="text"
                    placeholder="Issue title"
                    value={newIssueTitle}
                    onChange={(e) => setNewIssueTitle(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && handleAddIssue()}
                    className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm"
                    autoFocus
                  />
                  <button
                    onClick={handleAddIssue}
                    className="w-full py-2 bg-primary hover:bg-blue-600 rounded text-white text-sm font-medium transition-colors"
                  >
                    Add Issue
                  </button>
                </div>
              )}

              {/* Issues List */}
              <div className="space-y-1.5 max-h-96 overflow-y-auto">
                {issues.map((issue, index) => (
                  <motion.div
                    key={issue.id}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.03 }}
                    onClick={async () => {
                      if (currentIssue && currentIssue.id !== issue.id) {
                        await supabase
                          .from('issues')
                          .update({ status: currentIssue.status === 'completed' ? 'completed' : 'pending' })
                          .eq('id', currentIssue.id)
                      }
                      await supabase
                        .from('issues')
                        .update({ status: 'voting' })
                        .eq('id', issue.id)
                      await setStatus('voting')
                      setSelectedCard(null)
                      setHasVoted(false)
                    }}
                    className={`p-2.5 rounded cursor-pointer transition-colors border ${
                      issue.id === currentIssue?.id
                        ? 'bg-blue-light border-primary/30'
                        : 'bg-surface border-transparent hover:bg-neutral-light'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-secondary truncate">
                          {issue.title}
                        </p>
                        {issue.estimated_points && (
                          <p className="text-xs text-primary mt-0.5">
                            {issue.estimated_points} points
                          </p>
                        )}
                      </div>
                      <div
                        className={`w-2.5 h-2.5 rounded-full flex-shrink-0 mt-0.5 ${
                          issue.status === 'voting'
                            ? 'bg-success'
                            : issue.status === 'completed'
                            ? 'bg-primary'
                            : 'bg-neutral'
                        }`}
                      />
                    </div>
                  </motion.div>
                ))}
              </div>

              {issues.length === 0 && (
                <div className="text-center py-8">
                  <div className="w-12 h-12 rounded-full bg-neutral-light flex items-center justify-center mx-auto mb-3">
                    <svg className="w-6 h-6 text-neutral" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                    </svg>
                  </div>
                  <p className="text-neutral text-sm">No issues yet</p>
                  <p className="text-neutral text-xs mt-1">Click &quot;Add&quot; to create one</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
