'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { PokerCardDeck, FlyingCard } from './PokerCard'
import { PokerTable } from './PokerTable'
import { useGame } from '@/hooks/useGame'
import { usePlayer } from '@/hooks/usePlayer'
import { useWebSocketPresence } from '@/hooks/useWebSocketPresence'
import { useState, useEffect, useMemo, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { COFFEE_CARD, type Vote, type PlayerStreakStats, type Issue } from '@/types'
import { generateFunnyName } from '@/lib/funnyNames'

const LAST_GAME_ID_KEY = 'planning_poker_last_game_id'

interface GameRoomProps {
  gameId: string
  onToggleMode?: () => void
}

export function GameRoom({ gameId, onToggleMode }: GameRoomProps) {
  const router = useRouter()
  const { playerId, playerName, isAutoGenerated, isInitialized, updateName, syncPlayerId } = usePlayer()
  const { socket, isConnected, isPlayerActive, presence } = useWebSocketPresence(gameId, playerId, playerName || '')
  
  const { 
    game, 
    players, 
    issues, 
    votes, 
    isLoading, 
    error, 
    refreshGame, 
    updateGameStatus: setStatus, 
    setVotes,
    submitVote: submitVoteSocket,
    resetVotes: resetVotesSocket,
    createIssue: createIssueSocket,
    updateIssue: updateIssueSocket,
    deleteIssue: deleteIssueSocket,
    setCurrentIssue: setCurrentIssueSocket,
    socket: gameSocket,
    isConnected: isGameSocketConnected,
    // Gamification stats
    topStreakLeaders,
    shouldShowStreakStats,
    totalRevotes,
    votesResetKey,
  } = useGame(gameId, playerId, playerName || '')

  const [isJoining, setIsJoining] = useState(false)
  
  // Find current player from players list — match by ID first, fall back to name
  const currentPlayer = useMemo(() => {
    return players.find(p => p.id === playerId) || players.find(p => p.name === playerName) || null
  }, [players, playerId, playerName])

  // Show join modal only if user is not already in the game
  const [showJoinModal, setShowJoinModal] = useState(!currentPlayer)
  const [joinNameInput, setJoinNameInput] = useState('')
  const [selectedRole, setSelectedRole] = useState<'player' | 'viewer'>('player')
  
  // Generate default name for join modal
  useEffect(() => {
    if (isInitialized && !joinNameInput && !currentPlayer) {
      setJoinNameInput(generateFunnyName())
    }
  }, [isInitialized, currentPlayer])

  // Update showJoinModal when currentPlayer changes
  useEffect(() => {
    if (currentPlayer) {
      setShowJoinModal(false)
    }
  }, [currentPlayer])

  // Track viewer status from current player
  const isViewer = currentPlayer?.is_viewer ?? false

  // Debug presence
  useEffect(() => {
    console.log('Presence map:', Array.from(presence.entries()))
  }, [presence])
  
  const [selectedCard, setSelectedCard] = useState<number | typeof COFFEE_CARD | null>(null)
  const [hasVoted, setHasVoted] = useState(false)
  const [newIssueTitle, setNewIssueTitle] = useState('')
  const [showIssueInput, setShowIssueInput] = useState(false)
  const [showNameEditor, setShowNameEditor] = useState(false)
  const [nameEditInput, setNameEditInput] = useState('')
  
  // Mobile sidebar toggle state
  const [showSidebar, setShowSidebar] = useState(false)
  
  // Issue editing state
  const [editingIssueId, setEditingIssueId] = useState<string | null>(null)
  const [editIssueTitle, setEditIssueTitle] = useState('')
  
  // Streak stats panel state
  const [showStreakStats, setShowStreakStats] = useState(false)
  
  // Delete confirmation state
  const [deletingIssueId, setDeletingIssueId] = useState<string | null>(null)
  
  // Flying card animation state
  const [flyingCard, setFlyingCard] = useState<{
    value: number | typeof COFFEE_CARD
    startX: number
    startY: number
    endX: number
    endY: number
  } | null>(null)
  const [pendingVote, setPendingVote] = useState<{
    value: number | typeof COFFEE_CARD
    playerId: string
    issueId: string
    timestamp: number
  } | null>(null)
  const [wasRemoved, setWasRemoved] = useState(false)
  
  // Local state for which issue the user is viewing (not synced via WebSocket)
  // Each user can independently navigate and view different issues
  const [viewingIssueId, setViewingIssueId] = useState<string | null>(null)
  
  // Get the "active" issue from server (the one with status 'voting')
  // This is used for game workflow, not for viewing
  const serverActiveIssue = issues.find(i => i.status === 'voting')
  
  // Current issue being viewed - uses local state if set, otherwise falls back to server active issue
  const currentIssue = useMemo(() => {
    if (viewingIssueId) {
      return issues.find(i => i.id === viewingIssueId) || serverActiveIssue || issues[0]
    }
    return serverActiveIssue || issues[0]
  }, [issues, viewingIssueId, serverActiveIssue])
  
  const currentVotes = useMemo(() => {
    return currentIssue ? (votes[currentIssue.id] || []) : []
  }, [currentIssue, votes])

  // Determine if cards should be shown as revealed
  // - Always revealed if global game status is 'revealed'
  // - Also revealed if viewing a historical COMPLETED issue that has votes (even if global status is 'voting')
  // - NOT revealed for the current active voting issue (must click "Reveal" button)
  const isViewingRevealed = game?.status === 'revealed' || (currentIssue && currentIssue.status === 'completed' && currentVotes.length > 0)

  // Compute display status for issue tag
  // - "voted": issue has votes (indicates voting occurred on this issue)
  // - "completed": issue is completed but has no votes
  // - "voting": game is in voting state (including after revote)
  const getIssueDisplayStatus = useCallback((issue: Issue, issueVotes: Vote[]) => {
    const hasVotes = issueVotes && issueVotes.length > 0
    
    // Show "voted" if issue has any votes (historical voting occurred)
    if (hasVotes) {
      return 'voted'
    }
    if (issue.status === 'completed') {
      return 'completed'
    }
    return 'voting'
  }, [])

  // Check if current player has voted and detect if removed by someone else
  useEffect(() => {
    const existingPlayer = players.find(p => p.name === playerName)
    if (existingPlayer) {
      const playerHasVoted = !!currentVotes.some(v => v.player_id === existingPlayer.id)
      setHasVoted(playerHasVoted)
      
      // Clear pending vote once DB confirms the vote
      if (playerHasVoted && pendingVote && pendingVote.playerId === existingPlayer.id) {
        setPendingVote(null)
      }
    } else if (playerName && !wasRemoved && !isLoading) {
      // Player name exists but player not in list - they were removed by someone else
      // Only trigger this after initial load completes to avoid false positives during join
      console.log('Detected player removal by facilitator')
      setWasRemoved(true)
    }
  }, [currentVotes, players, playerName, pendingVote, wasRemoved, isLoading])

  // Reset voting state when issue changes
  useEffect(() => {
    setSelectedCard(null)
    setHasVoted(false)
  }, [currentIssue?.id])

  // Reset local voting state when votes are reset (by any player)
  // This ensures all players see cards reset when anyone clicks revote
  useEffect(() => {
    if (votesResetKey > 0) {
      setSelectedCard(null)
      setHasVoted(false)
      setPendingVote(null)
    }
  }, [votesResetKey])

  // Reset wasRemoved when game changes
  useEffect(() => {
    setWasRemoved(false)
  }, [gameId])

  const handleUpdateName = async () => {
    const newName = nameEditInput.trim()
    if (!newName) return

    const targetId = currentPlayer?.id || playerId
    if (!targetId) return

    console.log('Attempting to rename:', { targetId, newName, gameId, currentPlayer, playerId })

    // Check for duplicate (exact case-sensitive match like the DB constraint)
    const duplicate = players?.find((p: { name: string; id: string }) => p.name === newName && p.id !== targetId)
    
    if (duplicate) {
      console.log('Duplicate found:', duplicate)
      alert(`The name "${newName}" is already taken by player ID: ${duplicate.id}`)
      return
    }

    // Update via Socket.IO
    if (socket) {
      socket.emit('update-player-name', { playerId: targetId, newName }, (response: any) => {
        if (response.success) {
          updateName(newName)
          setShowNameEditor(false)
        } else {
          alert(`Failed to update name: ${response.error}`)
        }
      })
    }
  }

  const openNameEditor = () => {
    setNameEditInput(playerName)
    setShowNameEditor(true)
  }

  const handleRemovePlayer = async (playerIdToRemove: string) => {
    const currentPlayerData = players.find(p => p.name === playerName)
    const isFacilitator = currentPlayerData?.is_facilitator || false
    const isSelf = players.find(p => p.id === playerIdToRemove)?.name === playerName

    if (!isFacilitator && !isSelf) {
      alert('Only facilitators can remove other players')
      return
    }

    if (confirm('Are you sure you want to remove this player?')) {
      // Mark as removed if removing self to prevent auto-rejoin
      if (isSelf) {
        setWasRemoved(true)
      }
      
      if (socket) {
        socket.emit('remove-player', { playerId: playerIdToRemove, gameId }, (response: any) => {
          if (!response.success) {
            alert('Failed to remove player')
            if (isSelf) {
              setWasRemoved(false)
            }
          }
        })
      }
    }
  }

  const handleCardClick = async (value: number | typeof COFFEE_CARD, cardRect: DOMRect) => {
    if (!playerId) {
      alert('You need to join the game first.')
      return
    }
    // Allow changing card even if already voted (before reveal)
    if (game?.status === 'revealed') {
      alert('Voting has ended. Cannot change your vote.')
      return
    }

    // Check if player exists in this game
    // Use currentPlayer which handles fallback by name if playerId not found
    const existingPlayer = currentPlayer
    if (!existingPlayer) {
      // If still loading, wait for data to load
      if (isLoading) {
        console.log('Game still loading, please wait...')
        return
      }
      alert('You need to join the game first. Please refresh the page.')
      return
    }

    // Get card position (start of animation)
    const startPosition = {
      x: cardRect.left + cardRect.width / 2 - 28,
      y: cardRect.top + cardRect.height / 2 - 40,
    }

    // Find player's card slot on the table (end of animation)
    const playerCardEl = document.querySelector(`[data-player-card="${existingPlayer.id}"]`)
    let endPosition = { x: window.innerWidth / 2, y: window.innerHeight / 2 }
    
    if (playerCardEl) {
      const slotRect = playerCardEl.getBoundingClientRect()
      endPosition = {
        x: slotRect.left + slotRect.width / 2 - 28,
        y: slotRect.top + slotRect.height / 2 - 40,
      }
    }

    // Start flying card animation
    setFlyingCard({
      value,
      startX: cardRect.left + cardRect.width / 2 - 28,
      startY: cardRect.top + cardRect.height / 2 - 40,
      endX: endPosition.x,
      endY: endPosition.y,
    })
    setSelectedCard(value)
  }

  const handleFlyingCardComplete = async () => {
    if (!flyingCard) return

    const existingPlayer = players.find(p => p.name === playerName)
    if (!existingPlayer) return

    // Show face-down card immediately when animation completes (before DB submission)
    if (currentIssue) {
      setPendingVote({
        value: flyingCard.value,
        playerId: existingPlayer.id,
        issueId: currentIssue.id,
        timestamp: Date.now(),
      })
    }

    // Auto-create a default issue if none exists
    let issueId = currentIssue?.id
    if (!issueId) {
      // Create default issue via Socket.IO
      const title = 'Current Task'
      const order = issues.length
      if (socket) {
        socket.emit('create-issue', { gameId, title, order, status: 'voting' }, (response: any) => {
          if (response.success) {
            issueId = response.issue.id
            // Submit vote after issue is created
            submitVoteSocket(issueId, typeof flyingCard.value === 'number' ? flyingCard.value : -1)
            setHasVoted(true)
          } else {
            alert('Failed to create voting session')
            setSelectedCard(null)
          }
        })
      }
    } else {
      // Submit vote via Socket.IO
      await submitVoteSocket(issueId, typeof flyingCard.value === 'number' ? flyingCard.value : -1)
      setHasVoted(true)
    }

    // Clear flying card after submission
    setFlyingCard(null)
  }

  const handleReveal = async () => {
    if (!game) return
    await setStatus('revealed')
  }

  const handleResetVotes = async () => {
    if (!currentIssue) return
    // Emit reset-votes to server - all clients (including this one) will receive
    // 'votes-reset' broadcast and reset their local state via votesResetKey effect
    resetVotesSocket(currentIssue.id)
    await setStatus('voting')
    // DO NOT reset local state here - let the server broadcast handle it
    // This ensures ALL players see cards reset at the same time
  }

  const handleNextIssue = async () => {
    if (!currentIssue) return

    // Mark current issue as completed
    await updateIssueSocket(currentIssue.id, { status: 'completed' })

    // Find next pending issue
    const nextIssue = issues.find(i => i.status === 'pending' && i.id !== currentIssue.id)

    if (nextIssue) {
      await updateIssueSocket(nextIssue.id, { status: 'voting' })
      await setStatus('voting')
    } else {
      await setStatus('lobby')
    }

    // Clear local viewing state to follow the server-tracked active issue
    setViewingIssueId(null)
    setSelectedCard(null)
    setHasVoted(false)
  }

  const handleJoinGame = async () => {
    const name = joinNameInput.trim()
    if (!name) return

    setIsJoining(true)
    
    try {
      // Check for duplicate name
      const duplicate = players.find(p => p.name === name)
      if (duplicate) {
        alert(`The name "${name}" is already taken. Please choose another name.`)
        setIsJoining(false)
        return
      }

      // Create player via Socket.IO
      if (gameSocket && isGameSocketConnected) {
        gameSocket.emit('create-player', { gameId, playerName: name, isViewer: selectedRole === 'viewer' }, (response: any) => {
          if (response.success) {
            updateName(name)
            syncPlayerId(response.player.id)
            setShowJoinModal(false)
            // Refresh game data to ensure players list includes the newly created player
            // This fixes a race condition where player-joined event is broadcast before
            // the client's socket has joined the game room
            refreshGame()
          } else {
            alert(`Failed to join game: ${response.error}`)
          }
          setIsJoining(false)
        })
      }
    } catch (err) {
      console.error('Error joining game:', err)
      alert('Failed to join game. Please try again.')
      setIsJoining(false)
    }
  }

  const handleAddIssue = async () => {
    if (!newIssueTitle.trim()) return

    const isFirstIssue = issues.length === 0
    const title = newIssueTitle.trim()
    const order = issues.length
    
    // Create issue - first issue should be immediately votable (status 'voting')
    // Subsequent issues start as 'pending' until navigated to
    const issueStatus = isFirstIssue ? 'voting' : 'pending'
    await createIssueSocket(title, undefined, issueStatus)
    
    setNewIssueTitle('')
    setShowIssueInput(false)
    
    // Set game status to voting when first issue is added
    if (isFirstIssue) {
      await setStatus('voting')
      refreshGame()
    }
  }

  const handleDeleteIssue = async (issueId: string) => {
    if (confirm('Are you sure you want to remove this task?')) {
      await deleteIssueSocket(issueId)
      setDeletingIssueId(null)
    }
  }

  const handleClearVotedTasks = async () => {
    const votedIssueIds = issues
      .filter(issue => getIssueDisplayStatus(issue, votes[issue.id] || []) === 'voted')
      .map(issue => issue.id)
    
    if (votedIssueIds.length === 0) {
      alert('No voted tasks to clear.')
      return
    }
    
    if (confirm(`Remove all ${votedIssueIds.length} voted task(s)? This cannot be undone.`)) {
      for (const issueId of votedIssueIds) {
        await deleteIssueSocket(issueId)
      }
    }
  }

  const handleUpdateIssueTitle = async (issueId: string, newTitle: string) => {
    if (!newTitle.trim()) return

    await updateIssueSocket(issueId, { title: newTitle.trim() })
    setEditingIssueId(null)
    setEditIssueTitle('')
  }

  const startEditingIssue = (issue: { id: string; title: string }) => {
    setEditingIssueId(issue.id)
    setEditIssueTitle(issue.title)
  }

  const calculateConsensus = () => {
    if (currentVotes.length === 0) return null

    const numericVotes = currentVotes
      .map(v => v.points)
      .filter(p => p >= 0)

    if (numericVotes.length === 0) return null

    // Calculate mode (most frequent value)
    const counts: Record<number, number> = {}
    numericVotes.forEach(v => {
      counts[v] = (counts[v] || 0) + 1
    })
    
    let maxCount = 0
    let mode: number | null = null
    Object.entries(counts).forEach(([value, count]) => {
      if (count > maxCount) {
        maxCount = count
        mode = Number(value)
      }
    })
    
    // Build distribution string
    const distribution = Object.entries(counts)
      .sort((a, b) => Number(a[0]) - Number(b[0]))
      .map(([value, count]) => `${value} (${count} vote${count > 1 ? 's' : ''})`)
      .join(', ')

    const uniqueVotes = new Set(numericVotes)

    return {
      mode,
      modeCount: maxCount,
      consensus: uniqueVotes.size === 1,
      votes: numericVotes,
      coffeeBreaks: currentVotes.filter(v => v.points < 0).length,
      distribution,
      totalVotes: numericVotes.length,
    }
  }

  const consensus = calculateConsensus()

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-secondary text-lg">Loading game...</div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-error text-lg">{error}</div>
      </div>
    )
  }

  // Show join modal for new users
  if (showJoinModal && !currentPlayer) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-surface rounded-lg border border-border elevation-medium p-8 max-w-md w-full"
        >
          <h2 className="text-2xl font-semibold text-secondary mb-2">Join Game</h2>
          <p className="text-neutral mb-6">Choose your name and role to join the planning poker session.</p>
          
          <div className="space-y-6">
            {/* Name Input */}
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Your Name</label>
              <input
                type="text"
                value={joinNameInput}
                onChange={(e) => setJoinNameInput(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleJoinGame()}
                className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                autoFocus
                maxLength={30}
              />
              <p className="text-xs text-neutral mt-1">A random name has been generated for you. Feel free to change it!</p>
            </div>

            {/* Role Selection */}
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Select Your Role</label>
              <div className="grid grid-cols-2 gap-3">
                <button
                  onClick={() => setSelectedRole('player')}
                  className={`p-4 rounded-lg border-2 transition-all text-left ${
                    selectedRole === 'player'
                      ? 'border-primary bg-blue-light'
                      : 'border-border hover:border-neutral-light'
                  }`}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <svg className={`w-5 h-5 ${selectedRole === 'player' ? 'text-primary' : 'text-neutral'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                    <span className={`font-semibold ${selectedRole === 'player' ? 'text-primary' : 'text-secondary'}`}>Player</span>
                  </div>
                  <p className="text-xs text-neutral">Vote and participate in estimation</p>
                </button>
                
                <button
                  onClick={() => setSelectedRole('viewer')}
                  className={`p-4 rounded-lg border-2 transition-all text-left ${
                    selectedRole === 'viewer'
                      ? 'border-purple-500 bg-purple-50'
                      : 'border-border hover:border-neutral-light'
                  }`}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <svg className={`w-5 h-5 ${selectedRole === 'viewer' ? 'text-purple-500' : 'text-neutral'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    <span className={`font-semibold ${selectedRole === 'viewer' ? 'text-purple-600' : 'text-secondary'}`}>Viewer</span>
                  </div>
                  <p className="text-xs text-neutral">Watch without voting</p>
                </button>
              </div>
            </div>

            {/* Join Button */}
            <button
              onClick={handleJoinGame}
              disabled={!joinNameInput.trim() || isJoining}
              className="w-full py-3 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-semibold transition-colors"
            >
              {isJoining ? 'Joining...' : 'Join Game'}
            </button>
          </div>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="bg-surface border-b border-border elevation-low sticky top-0 z-50">
        <div className="px-4 py-3">
          {/* Top row: Game title and player count */}
          <div className="flex items-center justify-between mb-3">
            <div>
              <h1 className="text-lg font-semibold text-secondary">{game?.name}</h1>
              <p className="text-xs text-neutral">Game ID: {gameId}</p>
            </div>
            <div className="flex items-center gap-2">
              {/* Player count badge */}
              <div className="px-2 py-1 bg-neutral-light rounded text-xs font-medium text-secondary">
                {players.length} {players.length === 1 ? 'player' : 'players'}
              </div>
            </div>
          </div>
          
          {/* Bottom row: Scrollable player avatars and actions */}
          <div className="flex items-center gap-3">
            {/* Player avatars - scrollable on mobile */}
            <div className="flex -space-x-2 overflow-x-auto pb-1 flex-shrink-0">
              {players.map((player) => {
                const isActive = isPlayerActive(player.id)
                const isCurrentPlayer = player.name === playerName

                return (
                  <div key={player.id} className="relative group flex-shrink-0">
                    <div
                      className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold border-2 border-surface elevation-low ${
                        isActive ? 'bg-primary' : 'bg-neutral'
                      }`}
                      title={`${player.name} ${isActive ? '(online)' : '(offline)'}`}
                    >
                      {player.name.charAt(0).toUpperCase()}
                    </div>

                    {isActive && (
                      <div className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-success rounded-full border-2 border-surface" />
                    )}

                    {!isActive && (isCurrentPlayer || players.find(p => p.name === playerName)?.is_facilitator) && (
                      <button
                        onClick={() => handleRemovePlayer(player.id)}
                        className="absolute -top-2 -right-2 w-5 h-5 bg-error hover:bg-red-600 rounded-full flex items-center justify-center text-white text-xs opacity-0 group-hover:opacity-100 transition-opacity border-2 border-surface z-10"
                        title="Remove player"
                      >
                        ×
                      </button>
                    )}
                  </div>
                )
              })}
            </div>

            {/* Current player name with edit button */}
            <button
              onClick={openNameEditor}
              className="flex items-center gap-2 px-3 py-1.5 bg-neutral-light hover:bg-neutral-200 rounded transition-colors group flex-shrink-0"
              title="Click to edit your name"
            >
              <span className="text-neutral text-xs hidden sm:inline">Playing as:</span>
              <span className="text-secondary font-medium text-sm">{playerName}</span>
              <svg
                className="w-3.5 h-3.5 text-neutral group-hover:text-secondary transition-colors"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </svg>
            </button>

            {/* Simple Mode Toggle */}
            {onToggleMode && (
              <button
                onClick={onToggleMode}
                className="px-3 py-1.5 bg-neutral-light hover:bg-blue-50 text-neutral hover:text-primary rounded transition-colors text-sm font-medium flex-shrink-0 hidden sm:inline-block"
                title="Switch to Simple Mode"
              >
                Simple Mode
              </button>
            )}

            {/* Leave Game button */}
            <button
              onClick={() => {
                if (confirm('Leave this game? You can always rejoin later.')) {
                  localStorage.removeItem('planning_poker_last_game_id')
                  window.location.href = '/'
                }
              }}
              className="px-3 py-1.5 bg-neutral-light hover:bg-red-50 text-neutral hover:text-error rounded transition-colors text-sm font-medium flex-shrink-0"
              title="Leave game"
            >
              Leave
            </button>
          </div>
        </div>
      </header>

      {/* Name Editor Modal */}
      <AnimatePresence>
        {showNameEditor && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-neutral-dark/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setShowNameEditor(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-surface rounded-lg border border-border elevation-high p-6 max-w-md w-full"
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className="text-xl font-semibold text-secondary mb-2">Edit Your Name</h3>
              <p className="text-neutral text-sm mb-4">
                You were automatically assigned a fun name! Change it if you like.
              </p>
              <div className="space-y-4">
                <input
                  type="text"
                  value={nameEditInput}
                  onChange={(e) => setNameEditInput(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleUpdateName()}
                  className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                  autoFocus
                  maxLength={30}
                />
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowNameEditor(false)}
                    className="flex-1 py-2 bg-neutral-light hover:bg-neutral-200 rounded text-secondary font-medium transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleUpdateName}
                    disabled={!nameEditInput.trim() || nameEditInput.trim() === playerName}
                    className="flex-1 py-2 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-medium transition-colors"
                  >
                    Save
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="px-4 py-6">
        <div className="grid md:grid-cols-4 gap-6 max-w-7xl mx-auto">
          {/* Main Game Area - Full width on mobile, 3/4 on md */}
          <div className="md:col-span-3 space-y-6">
            {/* Mobile: Toggle sidebar button */}
            <div className="md:hidden mb-4">
              <button
                onClick={() => setShowSidebar(!showSidebar)}
                className="w-full py-2.5 bg-neutral-light hover:bg-neutral-200 rounded text-secondary font-medium transition-colors flex items-center justify-center gap-2"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                </svg>
                {showSidebar ? 'Hide Issues' : 'Show Issues'}
              </button>
            </div>
            {/* Current Issue */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-surface rounded-lg border border-border elevation-medium p-6"
            >
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h2 className="text-lg font-semibold text-secondary">
                    {currentIssue ? currentIssue.title : 'No Issue Selected'}
                  </h2>
                  <div className="flex items-center gap-2 mt-1 h-6">
                    {currentIssue ? (
                      <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
                        getIssueDisplayStatus(currentIssue, currentVotes) === 'voted'
                          ? 'bg-green-light text-success'
                          : getIssueDisplayStatus(currentIssue, currentVotes) === 'completed'
                          ? 'bg-green-light text-success'
                          : 'bg-blue-light text-primary'
                      }`}>
                        {getIssueDisplayStatus(currentIssue, currentVotes)}
                      </span>
                    ) : (
                      <span className="opacity-0 inline-flex items-center px-2 py-0.5 rounded text-xs font-medium">
                        placeholder
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {currentIssue?.description && (
                <p className="text-neutral mb-6">{currentIssue.description}</p>
              )}

              {/* Poker Table with Players */}
              <div className="mb-8">
                <PokerTable
                  players={currentPlayer && !players.find(p => p.id === currentPlayer.id) ? [...players, currentPlayer] : players}
                  currentPlayerName={playerName || ''}
                  currentPlayerId={currentPlayer?.id || null}
                  votes={votes}
                  currentIssueId={currentIssue?.id || null}
                  isRevealed={isViewingRevealed}
                  isPlayerActive={isPlayerActive}
                  gameId={gameId}
                  socket={gameSocket}
                  pendingVote={pendingVote}
                />
              </div>

              {/* Voting Cards - Hidden for viewers, shown when game is in voting/lobby state */}
              {/* Show when: game is in voting/lobby, user is not a viewer (treat undefined/null as not viewer) */}
              {(game?.status === 'voting' || game?.status === 'lobby') && !isViewer && (
                <div className="text-center border-t border-border pt-6">
                  <p className="text-neutral mb-4 h-6 flex items-center justify-center">
                    {hasVoted ? (
                      <span className="inline-flex items-center gap-1 animate-fade-in">
                        <svg className="w-4 h-4 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        Vote submitted! Change your vote anytime below
                      </span>
                    ) : (
                      <span className="opacity-0">Vote submitted! Change your vote anytime below</span>
                    )}
                  </p>
                  <PokerCardDeck
                    selectedValue={selectedCard}
                    onCardClick={handleCardClick}
                    disabled={flyingCard !== null}
                    animatingCard={flyingCard?.value ?? null}
                  />
                </div>
              )}

              {/* Viewer Message - Shown for viewers when game is in voting/lobby state */}
              {(game?.status === 'voting' || game?.status === 'lobby') && isViewer && (
                <div className="text-center border-t border-border pt-6">
                  <div className="inline-flex items-center gap-2 px-4 py-2 bg-purple-50 text-purple-700 rounded-lg">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    <span className="font-medium">You are in viewer mode - watching without voting</span>
                  </div>
                </div>
              )}

              {/* Flying Card Animation */}
              <AnimatePresence>
                {flyingCard && (
                  <FlyingCard
                    value={flyingCard.value}
                    startRect={{
                      left: flyingCard.startX,
                      top: flyingCard.startY,
                      width: 56,
                      height: 80,
                    }}
                    endRect={{
                      left: flyingCard.endX,
                      top: flyingCard.endY,
                      width: 56,
                      height: 80,
                    }}
                    onComplete={handleFlyingCardComplete}
                  />
                )}
              </AnimatePresence>

              {/* Reveal Phase Results - Shows when viewing an issue with votes */}
              {isViewingRevealed && currentVotes.length > 0 && (
                <div className="space-y-6 border-t border-border pt-6">
                  {/* Consensus Results */}
                  {consensus && (
                    <motion.div
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      className={`rounded-lg p-4 text-center border-2 ${
                        consensus.consensus
                          ? 'bg-green-light border-success/30'
                          : 'bg-yellow-light border-warning/30'
                      }`}
                    >
                      <h4 className="text-lg font-semibold text-secondary mb-2">
                        {consensus.consensus ? '🎉 Consensus Reached!' : '🤔 Different Estimates'}
                      </h4>
                      <p className="text-neutral mb-1">
                        Most Voted: <span className="font-bold text-primary text-2xl">{consensus.mode}</span> points
                      </p>
                      <p className="text-xs text-neutral mb-2">
                        {consensus.distribution}
                      </p>
                      {consensus.coffeeBreaks > 0 && (
                        <p className="text-neutral text-sm">
                          ☕ {consensus.coffeeBreaks} player(s) took a coffee break
                        </p>
                      )}
                    </motion.div>
                  )}
                  
                  {/* Streak Stats Panel - Shows when conditions are met */}
                  {shouldShowStreakStats && topStreakLeaders.length > 0 && (
                    <motion.div
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="rounded-lg border-2 border-purple-200 bg-gradient-to-br from-purple-50 to-pink-50 p-4"
                    >
                      <button
                        onClick={() => setShowStreakStats(!showStreakStats)}
                        className="w-full flex items-center justify-between text-left"
                      >
                        <div className="flex items-center gap-2">
                          <span className="text-lg">🔥</span>
                          <div>
                            <h4 className="text-base font-semibold text-purple-800">
                              Majority Streak Leaders
                            </h4>
                            <p className="text-xs text-purple-600">
                              Top players whose votes match the consensus
                            </p>
                          </div>
                        </div>
                        <svg
                          className={`w-5 h-5 text-purple-600 transition-transform ${showStreakStats ? 'rotate-180' : ''}`}
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                      
                      <AnimatePresence>
                        {showStreakStats && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: 'auto', opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ duration: 0.2 }}
                            className="overflow-hidden"
                          >
                            <div className="mt-4 space-y-3">
                              {topStreakLeaders.map((leader, index) => (
                                <motion.div
                                  key={leader.playerId}
                                  initial={{ x: -20, opacity: 0 }}
                                  animate={{ x: 0, opacity: 1 }}
                                  transition={{ delay: index * 0.1 }}
                                  className={`flex items-center gap-3 p-3 rounded-lg ${
                                    index === 0 ? 'bg-yellow-100 border border-yellow-300' : 'bg-white border border-purple-200'
                                  }`}
                                >
                                  <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-white ${
                                    index === 0 ? 'bg-yellow-500' : 'bg-purple-400'
                                  }`}>
                                    {index === 0 ? '👑' : `#${index + 1}`}
                                  </div>
                                  <div className="flex-1">
                                    <p className="font-semibold text-purple-900">{leader.playerName}</p>
                                    <p className="text-xs text-purple-600">
                                      {leader.majorityAlignments}/{leader.totalVotes} votes matched consensus
                                    </p>
                                  </div>
                                  <div className="text-right">
                                    <p className={`text-2xl font-bold ${
                                      index === 0 ? 'text-yellow-600' : 'text-purple-600'
                                    }`}>
                                      {leader.alignmentPercentage}%
                                    </p>
                                    <p className="text-[10px] text-purple-500">alignment</p>
                                  </div>
                                </motion.div>
                              ))}
                            </div>
                            <div className="mt-3 pt-3 border-t border-purple-200">
                              <p className="text-xs text-purple-600 text-center">
                                📊 Stats shown after 5+ completed issues or 3+ revotes
                              </p>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </motion.div>
                  )}

                  {/* Action Buttons - Show when viewing a revealed issue with votes, user is not a viewer */}
                  {currentIssue && (game?.status === 'revealed' || (currentIssue.status === 'completed' && currentVotes.length > 0)) && !currentPlayer?.is_viewer && (
                    <div className="flex justify-center gap-3">
                      <button
                        onClick={handleResetVotes}
                        className="px-5 py-2 bg-neutral-light hover:bg-neutral-200 rounded text-secondary font-medium transition-colors"
                      >
                        Revote
                      </button>
                      <button
                        onClick={handleNextIssue}
                        className="px-5 py-2 bg-primary hover:bg-blue-600 rounded text-white font-medium transition-colors"
                      >
                        Next Issue
                      </button>
                    </div>
                  )}
                </div>
              )}

              {/* Reveal Button - Only visible when viewing the active voting issue */}
              {(game?.status === 'voting' || game?.status === 'lobby') && currentIssue?.id === serverActiveIssue?.id && (
                <div className="text-center mt-6 pt-6 border-t border-border">
                  <button
                    onClick={handleReveal}
                    disabled={currentVotes.length === 0}
                    className="px-6 py-2.5 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-medium transition-colors"
                  >
                    Reveal Votes ({currentVotes.length} voted)
                  </button>
                </div>
              )}
            </motion.div>
          </div>

          {/* Sidebar - Issues List - Toggleable on mobile, always visible on md */}
          <div className={`md:col-span-1 ${showSidebar ? 'block' : 'hidden'} md:block`}>
            <div className="bg-surface rounded-lg border border-border elevation-medium p-4 max-h-[calc(100vh-120px)] md:max-h-96 overflow-y-auto">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-base font-semibold text-secondary">Issues</h3>
                <button
                  onClick={() => setShowIssueInput(!showIssueInput)}
                  className="px-2.5 py-1.5 bg-primary hover:bg-blue-600 rounded text-white text-sm font-medium transition-colors inline-flex items-center gap-1"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                  <span className="hidden sm:inline">Add</span>
                  <span className="sm:hidden">+</span>
                </button>
              </div>

              {/* Add Issue Input */}
              {showIssueInput && (
                <div className="mb-3 space-y-2">
                  <input
                    type="text"
                    placeholder="Issue title"
                    value={newIssueTitle}
                    onChange={(e) => setNewIssueTitle(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && handleAddIssue()}
                    className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm"
                    autoFocus
                  />
                  <button
                    onClick={handleAddIssue}
                    className="w-full py-2 bg-primary hover:bg-blue-600 rounded text-white text-sm font-medium transition-colors"
                  >
                    Add Issue
                  </button>
                </div>
              )}

              {/* Issues List */}
              <div className="space-y-1.5 max-h-96 overflow-y-auto">
                {issues.map((issue, index) => {
                  const issueVotes = votes[issue.id] || []
                  const isVoted = getIssueDisplayStatus(issue, issueVotes) === 'voted'
                  const isDeleting = deletingIssueId === issue.id
                  const isViewing = currentIssue?.id === issue.id
                  
                  return (
                    <motion.div
                      key={issue.id}
                      initial={{ opacity: 0, x: -10 }}
                      animate={isDeleting ? { opacity: 0, x: 100 } : { opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.03 }}
                      onClick={() => {
                        // Switch viewing locally - no WebSocket broadcast
                        // Each user can independently view any issue
                        setViewingIssueId(issue.id)
                        setSelectedCard(null)
                        setHasVoted(false)
                      }}
                      className={`p-2.5 rounded cursor-pointer transition-colors border group ${
                        isViewing
                          ? 'bg-blue-light border-primary/30'
                          : 'bg-surface border-transparent hover:bg-neutral-light'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-secondary truncate">
                            {issue.title}
                          </p>
                          {issue.estimated_points && (
                            <p className="text-xs text-primary mt-0.5">
                              {issue.estimated_points} points
                            </p>
                          )}
                        </div>
                        <div className="flex flex-col items-end gap-1">
                          {/* Voted badge */}
                          {isVoted && (
                            <span className="text-[10px] font-medium text-success bg-green-light px-1.5 py-0.5 rounded">
                              Voted
                            </span>
                          )}
                          {/* Delete button - shows on hover */}
                          <button
                            onClick={(e) => {
                              e.stopPropagation()
                              setDeletingIssueId(issue.id)
                              handleDeleteIssue(issue.id)
                            }}
                            className="opacity-0 group-hover:opacity-100 transition-opacity p-1 hover:bg-red-50 rounded text-neutral hover:text-error"
                            title="Remove task"
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                          </button>
                        </div>
                      </div>
                    </motion.div>
                  )
                })}
              </div>

              {issues.length === 0 && (
                <div className="text-center py-8">
                  <div className="w-12 h-12 rounded-full bg-neutral-light flex items-center justify-center mx-auto mb-3">
                    <svg className="w-6 h-6 text-neutral" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                    </svg>
                  </div>
                  <p className="text-neutral text-sm">No issues yet</p>
                  <p className="text-neutral text-xs mt-1">Click &quot;Add&quot; to create one</p>
                </div>
              )}

              {/* Clear Voted Tasks Button */}
              {issues.length > 0 && (
                <button
                  onClick={handleClearVotedTasks}
                  className="w-full mt-3 py-2 px-3 bg-red-50 hover:bg-red-100 text-error rounded text-sm font-medium transition-colors flex items-center justify-center gap-2"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  Clear Voted Tasks
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
