'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { PokerCardDeck, FlyingCard } from './PokerCard'
import { PokerTable } from './PokerTable'
import { useGame } from '@/hooks/useGame'
import { usePlayer } from '@/hooks/usePlayer'
import { useWebSocketPresence } from '@/hooks/useWebSocketPresence'
import { useState, useEffect, useMemo, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { COFFEE_CARD, type Vote } from '@/types'
import { generateFunnyName } from '@/lib/funnyNames'

const LAST_GAME_ID_KEY = 'planning_poker_last_game_id'

interface GameRoomProps {
  gameId: string
}

export function GameRoom({ gameId }: GameRoomProps) {
  const router = useRouter()
  const { playerId, playerName, isAutoGenerated, isInitialized, updateName, syncPlayerId } = usePlayer()
  const { socket, isConnected, isPlayerActive, presence } = useWebSocketPresence(gameId, playerId, playerName || '')
  
  const { 
    game, 
    players, 
    issues, 
    votes, 
    isLoading, 
    error, 
    refreshGame, 
    updateGameStatus: setStatus, 
    setVotes,
    submitVote: submitVoteSocket,
    resetVotes: resetVotesSocket,
    createIssue: createIssueSocket,
    updateIssue: updateIssueSocket,
    deleteIssue: deleteIssueSocket,
    setCurrentIssue: setCurrentIssueSocket,
    socket: gameSocket,
    isConnected: isGameSocketConnected,
  } = useGame(gameId, playerId, playerName || '')

  const [isJoining, setIsJoining] = useState(false)
  
  // Find current player from players list — match by ID first, fall back to name
  const currentPlayer = useMemo(() => {
    return players.find(p => p.id === playerId) || players.find(p => p.name === playerName) || null
  }, [players, playerId, playerName])

  // Show join modal only if user is not already in the game
  const [showJoinModal, setShowJoinModal] = useState(!currentPlayer)
  const [joinNameInput, setJoinNameInput] = useState('')
  const [selectedRole, setSelectedRole] = useState<'player' | 'viewer'>('player')
  
  // Generate default name for join modal
  useEffect(() => {
    if (isInitialized && !joinNameInput && !currentPlayer) {
      setJoinNameInput(generateFunnyName())
    }
  }, [isInitialized, currentPlayer])

  // Update showJoinModal when currentPlayer changes
  useEffect(() => {
    if (currentPlayer) {
      setShowJoinModal(false)
    }
  }, [currentPlayer])

  // Track viewer status from current player
  const isViewer = currentPlayer?.is_viewer ?? false

  // Debug presence
  useEffect(() => {
    console.log('Presence map:', Array.from(presence.entries()))
  }, [presence])
  
  const [selectedCard, setSelectedCard] = useState<number | typeof COFFEE_CARD | null>(null)
  const [hasVoted, setHasVoted] = useState(false)
  const [newIssueTitle, setNewIssueTitle] = useState('')
  const [showIssueInput, setShowIssueInput] = useState(false)
  const [showNameEditor, setShowNameEditor] = useState(false)
  const [nameEditInput, setNameEditInput] = useState('')
  
  // Issue editing state
  const [editingIssueId, setEditingIssueId] = useState<string | null>(null)
  const [editIssueTitle, setEditIssueTitle] = useState('')
  
  // Flying card animation state
  const [flyingCard, setFlyingCard] = useState<{
    value: number | typeof COFFEE_CARD
    startX: number
    startY: number
    endX: number
    endY: number
  } | null>(null)
  const [pendingVote, setPendingVote] = useState<{
    value: number | typeof COFFEE_CARD
    playerId: string
    issueId: string
    timestamp: number
  } | null>(null)
  const [wasRemoved, setWasRemoved] = useState(false)

  const currentIssue = issues.find(i => i.status === 'voting') || issues[0]
  const currentVotes = useMemo(() => {
    return currentIssue ? (votes[currentIssue.id] || []) : []
  }, [currentIssue, votes])

  // Check if current player has voted and detect if removed by someone else
  useEffect(() => {
    const existingPlayer = players.find(p => p.name === playerName)
    if (existingPlayer) {
      const playerHasVoted = !!currentVotes.some(v => v.player_id === existingPlayer.id)
      setHasVoted(playerHasVoted)
      
      // Clear pending vote once DB confirms the vote
      if (playerHasVoted && pendingVote && pendingVote.playerId === existingPlayer.id) {
        setPendingVote(null)
      }
    } else if (playerName && !wasRemoved) {
      // Player name exists but player not in list - they were removed by someone else
      console.log('Detected player removal by facilitator')
      setWasRemoved(true)
    }
  }, [currentVotes, players, playerName, pendingVote, wasRemoved])

  // Reset voting state when issue changes
  useEffect(() => {
    setSelectedCard(null)
    setHasVoted(false)
  }, [currentIssue?.id])

  // Reset wasRemoved when game changes
  useEffect(() => {
    setWasRemoved(false)
  }, [gameId])

  const handleUpdateName = async () => {
    const newName = nameEditInput.trim()
    if (!newName) return

    const targetId = currentPlayer?.id || playerId
    if (!targetId) return

    console.log('Attempting to rename:', { targetId, newName, gameId, currentPlayer, playerId })

    // Check for duplicate (exact case-sensitive match like the DB constraint)
    const duplicate = players?.find((p: { name: string; id: string }) => p.name === newName && p.id !== targetId)
    
    if (duplicate) {
      console.log('Duplicate found:', duplicate)
      alert(`The name "${newName}" is already taken by player ID: ${duplicate.id}`)
      return
    }

    // Update via Socket.IO
    if (socket) {
      socket.emit('update-player-name', { playerId: targetId, newName }, (response: any) => {
        if (response.success) {
          updateName(newName)
          setShowNameEditor(false)
        } else {
          alert(`Failed to update name: ${response.error}`)
        }
      })
    }
  }

  const openNameEditor = () => {
    setNameEditInput(playerName)
    setShowNameEditor(true)
  }

  const handleRemovePlayer = async (playerIdToRemove: string) => {
    const currentPlayerData = players.find(p => p.name === playerName)
    const isFacilitator = currentPlayerData?.is_facilitator || false
    const isSelf = players.find(p => p.id === playerIdToRemove)?.name === playerName

    if (!isFacilitator && !isSelf) {
      alert('Only facilitators can remove other players')
      return
    }

    if (confirm('Are you sure you want to remove this player?')) {
      // Mark as removed if removing self to prevent auto-rejoin
      if (isSelf) {
        setWasRemoved(true)
      }
      
      if (socket) {
        socket.emit('remove-player', { playerId: playerIdToRemove, gameId }, (response: any) => {
          if (!response.success) {
            alert('Failed to remove player')
            if (isSelf) {
              setWasRemoved(false)
            }
          }
        })
      }
    }
  }

  const handleCardClick = async (value: number | typeof COFFEE_CARD, cardRect: DOMRect) => {
    if (!playerId) {
      alert('You need to join the game first.')
      return
    }
    // Allow changing card even if already voted (before reveal)
    if (game?.status === 'revealed') {
      alert('Voting has ended. Cannot change your vote.')
      return
    }

    // Check if player exists in this game
    const existingPlayer = players.find(p => p.name === playerName)
    if (!existingPlayer) {
      alert('You need to join the game first. Please refresh the page.')
      return
    }

    // Get card position (start of animation)
    const startPosition = {
      x: cardRect.left + cardRect.width / 2 - 28,
      y: cardRect.top + cardRect.height / 2 - 40,
    }

    // Find player's card slot on the table (end of animation)
    const playerCardEl = document.querySelector(`[data-player-card="${existingPlayer.id}"]`)
    let endPosition = { x: window.innerWidth / 2, y: window.innerHeight / 2 }
    
    if (playerCardEl) {
      const slotRect = playerCardEl.getBoundingClientRect()
      endPosition = {
        x: slotRect.left + slotRect.width / 2 - 28,
        y: slotRect.top + slotRect.height / 2 - 40,
      }
    }

    // Start flying card animation
    setFlyingCard({
      value,
      startX: cardRect.left + cardRect.width / 2 - 28,
      startY: cardRect.top + cardRect.height / 2 - 40,
      endX: endPosition.x,
      endY: endPosition.y,
    })
    setSelectedCard(value)
  }

  const handleFlyingCardComplete = async () => {
    if (!flyingCard) return

    const existingPlayer = players.find(p => p.name === playerName)
    if (!existingPlayer) return

    // Show face-down card immediately when animation completes (before DB submission)
    if (currentIssue) {
      setPendingVote({
        value: flyingCard.value,
        playerId: existingPlayer.id,
        issueId: currentIssue.id,
        timestamp: Date.now(),
      })
    }

    // Auto-create a default issue if none exists
    let issueId = currentIssue?.id
    if (!issueId) {
      // Create default issue via Socket.IO
      const title = 'Current Task'
      const order = issues.length
      if (socket) {
        socket.emit('create-issue', { gameId, title, order, status: 'voting' }, (response: any) => {
          if (response.success) {
            issueId = response.issue.id
            // Submit vote after issue is created
            submitVoteSocket(issueId, typeof flyingCard.value === 'number' ? flyingCard.value : -1)
            setHasVoted(true)
          } else {
            alert('Failed to create voting session')
            setSelectedCard(null)
          }
        })
      }
    } else {
      // Submit vote via Socket.IO
      await submitVoteSocket(issueId, typeof flyingCard.value === 'number' ? flyingCard.value : -1)
      setHasVoted(true)
    }

    // Clear flying card after submission
    setFlyingCard(null)
  }

  const handleReveal = async () => {
    if (!game) return
    await setStatus('revealed')
  }

  const handleResetVotes = async () => {
    if (!currentIssue) return
    await resetVotesSocket(currentIssue.id)
    await setStatus('voting')
    // Clear local votes immediately to update UI
    setVotes(prev => ({ ...prev, [currentIssue.id]: [] }))
    setSelectedCard(null)
    setHasVoted(false)
  }

  const handleNextIssue = async () => {
    if (!currentIssue) return

    // Mark current issue as completed
    await updateIssueSocket(currentIssue.id, { status: 'completed' })

    // Find next pending issue
    const nextIssue = issues.find(i => i.status === 'pending' && i.id !== currentIssue.id)

    if (nextIssue) {
      await updateIssueSocket(nextIssue.id, { status: 'voting' })
      await setStatus('voting')
    } else {
      await setStatus('lobby')
    }

    setSelectedCard(null)
    setHasVoted(false)
  }

  const handleJoinGame = async () => {
    const name = joinNameInput.trim()
    if (!name) return

    setIsJoining(true)
    
    try {
      // Check for duplicate name
      const duplicate = players.find(p => p.name === name)
      if (duplicate) {
        alert(`The name "${name}" is already taken. Please choose another name.`)
        setIsJoining(false)
        return
      }

      // Create player via Socket.IO
      if (gameSocket && isGameSocketConnected) {
        gameSocket.emit('create-player', { gameId, playerName: name, isViewer: selectedRole === 'viewer' }, (response: any) => {
          if (response.success) {
            updateName(name)
            syncPlayerId(response.player.id)
            setShowJoinModal(false)
          } else {
            alert(`Failed to join game: ${response.error}`)
          }
          setIsJoining(false)
        })
      }
    } catch (err) {
      console.error('Error joining game:', err)
      alert('Failed to join game. Please try again.')
      setIsJoining(false)
    }
  }

  const handleAddIssue = async () => {
    if (!newIssueTitle.trim()) return

    const isFirstIssue = issues.length === 0
    const title = newIssueTitle.trim()
    const order = issues.length
    
    await createIssueSocket(title, undefined)
    
    setNewIssueTitle('')
    setShowIssueInput(false)
    
    // Set game status to voting when first issue is added
    if (isFirstIssue) {
      await setStatus('voting')
      refreshGame()
    }
  }

  const handleUpdateIssueTitle = async (issueId: string, newTitle: string) => {
    if (!newTitle.trim()) return

    await updateIssueSocket(issueId, { title: newTitle.trim() })
    setEditingIssueId(null)
    setEditIssueTitle('')
  }

  const startEditingIssue = (issue: { id: string; title: string }) => {
    setEditingIssueId(issue.id)
    setEditIssueTitle(issue.title)
  }

  const calculateConsensus = () => {
    if (currentVotes.length === 0) return null

    const numericVotes = currentVotes
      .map(v => v.points)
      .filter(p => p >= 0)

    if (numericVotes.length === 0) return null

    const avg = numericVotes.reduce((a, b) => a + b, 0) / numericVotes.length
    const uniqueVotes = new Set(numericVotes)

    return {
      average: avg.toFixed(1),
      consensus: uniqueVotes.size === 1,
      votes: numericVotes,
      coffeeBreaks: currentVotes.filter(v => v.points < 0).length,
    }
  }

  const consensus = calculateConsensus()

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-secondary text-lg">Loading game...</div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-error text-lg">{error}</div>
      </div>
    )
  }

  // Show join modal for new users
  if (showJoinModal && !currentPlayer) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-surface rounded-lg border border-border elevation-medium p-8 max-w-md w-full"
        >
          <h2 className="text-2xl font-semibold text-secondary mb-2">Join Game</h2>
          <p className="text-neutral mb-6">Choose your name and role to join the planning poker session.</p>
          
          <div className="space-y-6">
            {/* Name Input */}
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Your Name</label>
              <input
                type="text"
                value={joinNameInput}
                onChange={(e) => setJoinNameInput(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleJoinGame()}
                className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                autoFocus
                maxLength={30}
              />
              <p className="text-xs text-neutral mt-1">A random name has been generated for you. Feel free to change it!</p>
            </div>

            {/* Role Selection */}
            <div>
              <label className="block text-sm font-medium text-secondary mb-2">Select Your Role</label>
              <div className="grid grid-cols-2 gap-3">
                <button
                  onClick={() => setSelectedRole('player')}
                  className={`p-4 rounded-lg border-2 transition-all text-left ${
                    selectedRole === 'player'
                      ? 'border-primary bg-blue-light'
                      : 'border-border hover:border-neutral-light'
                  }`}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <svg className={`w-5 h-5 ${selectedRole === 'player' ? 'text-primary' : 'text-neutral'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                    <span className={`font-semibold ${selectedRole === 'player' ? 'text-primary' : 'text-secondary'}`}>Player</span>
                  </div>
                  <p className="text-xs text-neutral">Vote and participate in estimation</p>
                </button>
                
                <button
                  onClick={() => setSelectedRole('viewer')}
                  className={`p-4 rounded-lg border-2 transition-all text-left ${
                    selectedRole === 'viewer'
                      ? 'border-purple-500 bg-purple-50'
                      : 'border-border hover:border-neutral-light'
                  }`}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <svg className={`w-5 h-5 ${selectedRole === 'viewer' ? 'text-purple-500' : 'text-neutral'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    <span className={`font-semibold ${selectedRole === 'viewer' ? 'text-purple-600' : 'text-secondary'}`}>Viewer</span>
                  </div>
                  <p className="text-xs text-neutral">Watch without voting</p>
                </button>
              </div>
            </div>

            {/* Join Button */}
            <button
              onClick={handleJoinGame}
              disabled={!joinNameInput.trim() || isJoining}
              className="w-full py-3 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-semibold transition-colors"
            >
              {isJoining ? 'Joining...' : 'Join Game'}
            </button>
          </div>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="bg-surface border-b border-border elevation-low sticky top-0 z-50">
        <div className="px-4 py-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div>
                <h1 className="text-lg font-semibold text-secondary">{game?.name}</h1>
                <p className="text-xs text-neutral">Game ID: {gameId}</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              {/* Player avatars */}
              <div className="flex -space-x-2">
                {players.map((player) => {
                  const isActive = isPlayerActive(player.id)
                  const isCurrentPlayer = player.name === playerName

                  return (
                    <div key={player.id} className="relative group">
                      <div
                        className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold border-2 border-surface elevation-low ${
                          isActive ? 'bg-primary' : 'bg-neutral'
                        }`}
                        title={`${player.name} ${isActive ? '(online)' : '(offline)'}`}
                      >
                        {player.name.charAt(0).toUpperCase()}
                      </div>

                      {isActive && (
                        <div className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-success rounded-full border-2 border-surface" />
                      )}

                      {!isActive && (isCurrentPlayer || players.find(p => p.name === playerName)?.is_facilitator) && (
                        <button
                          onClick={() => handleRemovePlayer(player.id)}
                          className="absolute -top-2 -right-2 w-5 h-5 bg-error hover:bg-red-600 rounded-full flex items-center justify-center text-white text-xs opacity-0 group-hover:opacity-100 transition-opacity border-2 border-surface z-10"
                          title="Remove player"
                        >
                          ×
                        </button>
                      )}
                    </div>
                  )
                })}
              </div>

              {/* Player count badge */}
              <div className="px-2 py-1 bg-neutral-light rounded text-xs font-medium text-secondary">
                {players.length} {players.length === 1 ? 'player' : 'players'}
              </div>

              {/* Current player name with edit button */}
              <button
                onClick={openNameEditor}
                className="flex items-center gap-2 px-3 py-1.5 bg-neutral-light hover:bg-neutral-200 rounded transition-colors group"
                title="Click to edit your name"
              >
                <span className="text-neutral text-xs">Playing as:</span>
                <span className="text-secondary font-medium text-sm">{playerName}</span>
                <svg
                  className="w-3.5 h-3.5 text-neutral group-hover:text-secondary transition-colors"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                </svg>
              </button>

              {/* Leave Game button */}
              <button
                onClick={() => {
                  if (confirm('Leave this game? You can always rejoin later.')) {
                    localStorage.removeItem('planning_poker_last_game_id')
                    window.location.href = '/'
                  }
                }}
                className="px-3 py-1.5 bg-neutral-light hover:bg-red-50 text-neutral hover:text-error rounded transition-colors text-sm font-medium"
                title="Leave game"
              >
                Leave
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Name Editor Modal */}
      <AnimatePresence>
        {showNameEditor && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-neutral-dark/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setShowNameEditor(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-surface rounded-lg border border-border elevation-high p-6 max-w-md w-full"
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className="text-xl font-semibold text-secondary mb-2">Edit Your Name</h3>
              <p className="text-neutral text-sm mb-4">
                You were automatically assigned a fun name! Change it if you like.
              </p>
              <div className="space-y-4">
                <input
                  type="text"
                  value={nameEditInput}
                  onChange={(e) => setNameEditInput(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleUpdateName()}
                  className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                  autoFocus
                  maxLength={30}
                />
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowNameEditor(false)}
                    className="flex-1 py-2 bg-neutral-light hover:bg-neutral-200 rounded text-secondary font-medium transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleUpdateName}
                    disabled={!nameEditInput.trim() || nameEditInput.trim() === playerName}
                    className="flex-1 py-2 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-medium transition-colors"
                  >
                    Save
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="px-4 py-6">
        <div className="grid lg:grid-cols-4 gap-6 max-w-7xl mx-auto">
          {/* Main Game Area */}
          <div className="lg:col-span-3 space-y-6">
            {/* Current Issue */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-surface rounded-lg border border-border elevation-medium p-6"
            >
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h2 className="text-lg font-semibold text-secondary">
                    {currentIssue ? currentIssue.title : 'No Issue Selected'}
                  </h2>
                  <div className="flex items-center gap-2 mt-1 h-6">
                    {currentIssue ? (
                      <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
                        currentIssue.status === 'voting'
                          ? 'bg-blue-light text-primary'
                          : currentIssue.status === 'completed'
                          ? 'bg-green-light text-success'
                          : 'bg-neutral-light text-neutral'
                      }`}>
                        {currentIssue.status}
                      </span>
                    ) : (
                      <span className="opacity-0 inline-flex items-center px-2 py-0.5 rounded text-xs font-medium">
                        placeholder
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {currentIssue?.description && (
                <p className="text-neutral mb-6">{currentIssue.description}</p>
              )}

              {/* Poker Table with Players */}
              <div className="mb-8">
                <PokerTable
                  players={players}
                  currentPlayerName={playerName || ''}
                  currentPlayerId={currentPlayer?.id || null}
                  votes={votes}
                  currentIssueId={currentIssue?.id || null}
                  isRevealed={game?.status === 'revealed'}
                  isPlayerActive={isPlayerActive}
                  gameId={gameId}
                  socket={gameSocket}
                  pendingVote={pendingVote}
                />
              </div>

              {/* Voting Cards - Hidden for viewers */}
              {(game?.status === 'voting' || game?.status === 'lobby') && !isViewer && (
                <div className="text-center border-t border-border pt-6">
                  <p className="text-neutral mb-4 h-6 flex items-center justify-center">
                    {hasVoted ? (
                      <span className="inline-flex items-center gap-1 animate-fade-in">
                        <svg className="w-4 h-4 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        Vote submitted! Change your vote anytime below
                      </span>
                    ) : (
                      <span className="opacity-0">Vote submitted! Change your vote anytime below</span>
                    )}
                  </p>
                  <PokerCardDeck
                    selectedValue={selectedCard}
                    onCardClick={handleCardClick}
                    disabled={flyingCard !== null}
                    animatingCard={flyingCard?.value ?? null}
                  />
                </div>
              )}

              {/* Viewer Message */}
              {(game?.status === 'voting' || game?.status === 'lobby') && isViewer && (
                <div className="text-center border-t border-border pt-6">
                  <div className="inline-flex items-center gap-2 px-4 py-2 bg-purple-50 text-purple-700 rounded-lg">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    <span className="font-medium">You are in viewer mode - watching without voting</span>
                  </div>
                </div>
              )}

              {/* Flying Card Animation */}
              <AnimatePresence>
                {flyingCard && (
                  <FlyingCard
                    value={flyingCard.value}
                    startRect={{
                      left: flyingCard.startX,
                      top: flyingCard.startY,
                      width: 56,
                      height: 80,
                    }}
                    endRect={{
                      left: flyingCard.endX,
                      top: flyingCard.endY,
                      width: 56,
                      height: 80,
                    }}
                    onComplete={handleFlyingCardComplete}
                  />
                )}
              </AnimatePresence>

              {/* Reveal Phase Results */}
              {game?.status === 'revealed' && currentVotes.length > 0 && (
                <div className="space-y-6 border-t border-border pt-6">
                  {/* Consensus Results */}
                  {consensus && (
                    <motion.div
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      className={`rounded-lg p-4 text-center border-2 ${
                        consensus.consensus
                          ? 'bg-green-light border-success/30'
                          : 'bg-yellow-light border-warning/30'
                      }`}
                    >
                      <h4 className="text-lg font-semibold text-secondary mb-2">
                        {consensus.consensus ? '🎉 Consensus Reached!' : '🤔 Different Estimates'}
                      </h4>
                      <p className="text-neutral mb-1">
                        Average: <span className="font-bold text-primary">{consensus.average}</span> points
                      </p>
                      {consensus.coffeeBreaks > 0 && (
                        <p className="text-neutral text-sm">
                          ☕ {consensus.coffeeBreaks} player(s) took a coffee break
                        </p>
                      )}
                    </motion.div>
                  )}

                  {/* Action Buttons */}
                  <div className="flex justify-center gap-3">
                    <button
                      onClick={handleResetVotes}
                      className="px-5 py-2 bg-neutral-light hover:bg-neutral-200 rounded text-secondary font-medium transition-colors"
                    >
                      Revote
                    </button>
                    <button
                      onClick={handleNextIssue}
                      className="px-5 py-2 bg-primary hover:bg-blue-600 rounded text-white font-medium transition-colors"
                    >
                      Next Issue
                    </button>
                  </div>
                </div>
              )}

              {/* Reveal Button - Always visible, disabled when no votes */}
              {(game?.status === 'voting' || game?.status === 'lobby') && (
                <div className="text-center mt-6 pt-6 border-t border-border">
                  <button
                    onClick={handleReveal}
                    disabled={currentVotes.length === 0}
                    className="px-6 py-2.5 bg-primary hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed rounded text-white font-medium transition-colors"
                  >
                    Reveal Votes ({currentVotes.length} voted)
                  </button>
                </div>
              )}
            </motion.div>
          </div>

          {/* Sidebar - Issues List */}
          <div className="lg:col-span-1">
            <div className="bg-surface rounded-lg border border-border elevation-medium p-4 sticky top-20">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-base font-semibold text-secondary">Issues</h3>
                <button
                  onClick={() => setShowIssueInput(!showIssueInput)}
                  className="px-2.5 py-1.5 bg-primary hover:bg-blue-600 rounded text-white text-sm font-medium transition-colors inline-flex items-center gap-1"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                  Add
                </button>
              </div>

              {/* Add Issue Input */}
              {showIssueInput && (
                <div className="mb-3 space-y-2">
                  <input
                    type="text"
                    placeholder="Issue title"
                    value={newIssueTitle}
                    onChange={(e) => setNewIssueTitle(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && handleAddIssue()}
                    className="w-full px-3 py-2 rounded border border-border text-secondary placeholder-neutral focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm"
                    autoFocus
                  />
                  <button
                    onClick={handleAddIssue}
                    className="w-full py-2 bg-primary hover:bg-blue-600 rounded text-white text-sm font-medium transition-colors"
                  >
                    Add Issue
                  </button>
                </div>
              )}

              {/* Issues List */}
              <div className="space-y-1.5 max-h-96 overflow-y-auto">
                {issues.map((issue, index) => (
                  <motion.div
                    key={issue.id}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.03 }}
                    onClick={async () => {
                      if (currentIssue && currentIssue.id !== issue.id) {
                        await updateIssueSocket(currentIssue.id, { 
                          status: currentIssue.status === 'completed' ? 'completed' : 'pending' 
                        })
                      }
                      await updateIssueSocket(issue.id, { status: 'voting' })
                      await setStatus('voting')
                      setSelectedCard(null)
                      setHasVoted(false)
                    }}
                    className={`p-2.5 rounded cursor-pointer transition-colors border ${
                      issue.id === currentIssue?.id
                        ? 'bg-blue-light border-primary/30'
                        : 'bg-surface border-transparent hover:bg-neutral-light'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-secondary truncate">
                          {issue.title}
                        </p>
                        {issue.estimated_points && (
                          <p className="text-xs text-primary mt-0.5">
                            {issue.estimated_points} points
                          </p>
                        )}
                      </div>
                      <div
                        className={`w-2.5 h-2.5 rounded-full flex-shrink-0 mt-0.5 ${
                          issue.status === 'voting'
                            ? 'bg-success'
                            : issue.status === 'completed'
                            ? 'bg-primary'
                            : 'bg-neutral'
                        }`}
                      />
                    </div>
                  </motion.div>
                ))}
              </div>

              {issues.length === 0 && (
                <div className="text-center py-8">
                  <div className="w-12 h-12 rounded-full bg-neutral-light flex items-center justify-center mx-auto mb-3">
                    <svg className="w-6 h-6 text-neutral" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                    </svg>
                  </div>
                  <p className="text-neutral text-sm">No issues yet</p>
                  <p className="text-neutral text-xs mt-1">Click &quot;Add&quot; to create one</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
